{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "ConappsCMX-Backend API",
    "description": "ConappsCMX-Backend API"
  },
  "host": "localhost:3002",
  "basePath": "/v1",
  "schemes": ["http"],
  "tags": [
    {
      "name": "Passport",
      "description": " -API Passport provider = [cognito, facebook, google]-"
    },
    {
      "name": "AWS",
      "description": " -API AWS Cognito"
    },
    {
      "name": "Access Points",
      "description": "Metodos para los Puntos de Acceso"
    },
    {
      "name": "Locations",
      "description": "Metodos para las Ubicaciones"
    },
    {
      "name": "Profiles",
      "description": "Metodos para los Perfiles de Usuarios"
    },
    {
      "name": "Widgets",
      "description": "Informacion para realizar las graficas"
    }
  ],
  "paths": {
    "/aps": {
      "get": {
        "tags": ["Access Points"],
        "summary": "Devuelve una lista de Puntos de Acceso.",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ArrayOfAps"
            }
          }
        }
      },
      "post": {
        "tags": ["Access Points"],
        "summary": "Para crear un nuevo Punto de Acceso.",
        "description": "Para crear un nuevo Punto de Acceso",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "description": "Parametros para la creacion de Puntos de Accesos",
            "schema": {
              "$ref": "#/definitions/APspost"
            }
          }
        ],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Punto de Acceso Creado",
            "schema": {
              "$ref": "#/definitions/APs"
            }
          }
        }
      },
      "put": {
        "summary": "Actualizar Punto de Acceso dado su ID",
        "tags": ["Access Points"],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "description": "Punto de Acceso con nuevas propiedades",
            "schema": {
              "$ref": "#/definitions/APsput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Punto de Acceso actualizado",
            "schema": {
              "$ref": "#/definitions/APsput2"
            }
          }
        }
      },
      "delete": {
        "summary": "Eliminar Punto de Acceso dado su ID",
        "tags": ["Access Points"],
        "parameters": [
          {
            "name": "id",
            "in": "body",
            "description": "Id de AP a borrar",
            "schema": {
              "$ref": "#/definitions/APsdelete"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Punto de Acceso borrado"
          }
        }
      }
    },
    "/locations": {
      "get": {
        "tags": ["Locations"],
        "summary": "Devuelve una lista de Ubucaciones.",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ArrayOfLocations"
            }
          }
        }
      },
      "post": {
        "tags": ["Locations"],
        "summary": "Para crear una nueva Ubucacion.",
        "description": "Para crear una nueva Ubucacion",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "description": "Parametros para la creacion de Ubucaciones",
            "schema": {
              "$ref": "#/definitions/Locationspost"
            }
          }
        ],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Ubucacion Creada",
            "schema": {
              "$ref": "#/definitions/Locations"
            }
          }
        }
      },
      "put": {
        "summary": "Actualizar Ubucacion dado su ID",
        "tags": ["Locations"],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "description": "Nuevas propiedades de Ubicacion",
            "schema": {
              "$ref": "#/definitions/Locationsput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ubucacion actualizada",
            "schema": {
              "$ref": "#/definitions/Locationsput2"
            }
          }
        }
      },
      "delete": {
        "summary": "Eliminar Ubucacion dado su ID",
        "tags": ["Locations"],
        "parameters": [
          {
            "name": "id",
            "in": "body",
            "description": "Id de ubucacion a borrar",
            "schema": {
              "$ref": "#/definitions/Locationsdelete"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ubucacion eliminada"
          }
        }
      }
    },
    "/profiles": {
      "get": {
        "tags": ["Profiles"],
        "summary": "Devuelve una lista de Perfiles.",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ArrayOfProfiles"
            }
          }
        }
      },
      "post": {
        "tags": ["Profiles"],
        "summary": "Para crear un nuevo Perfil.",
        "description": "Para crear un nuevo Perfil",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "description": "Parametros para la creacion de Perfiles",
            "schema": {
              "$ref": "#/definitions/Profilespost"
            }
          }
        ],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Perfil Creado",
            "schema": {
              "$ref": "#/definitions/Profiles"
            }
          }
        }
      },
      "put": {
        "summary": "Actualizar Perfil dado su ID",
        "tags": ["Profiles"],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "description": "Perfil con nuevos valores",
            "schema": {
              "$ref": "#/definitions/Profilesput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Perfil actualizado",
            "schema": {
              "$ref": "#/definitions/Profilesput2"
            }
          }
        }
      },
      "delete": {
        "summary": "Eliminar Perfil dado su ID",
        "parameters": [
          {
            "name": "id",
            "in": "body",
            "description": "id de perfil a borrar",
            "schema": {
              "$ref": "#/definitions/Profilesdelete"
            }
          }
        ],
        "tags": ["Profiles"],
        "responses": {
          "200": {
            "description": "El Perfil es borrado"
          }
        }
      }
    },
    "/locations/show": {
      "get": {
        "summary": "Muestra una Ubucacion",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "El id de la ubicacion ",
            "required": true,
            "type": "string"
          }
        ],
        "tags": ["Locations"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Locations"
            }
          }
        }
      }
    },
    "/aps/show": {
      "get": {
        "summary": "Muestra una punto de acceso",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "El id del punto de acceso ",
            "required": true,
            "type": "string"
          }
        ],
        "tags": ["Access Points"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/APs"
            }
          }
        }
      }
    },
    "/profiles/show": {
      "get": {
        "summary": "Muestra una Ubucacion",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "El id del perfil",
            "required": true,
            "type": "string"
          }
        ],
        "tags": ["Profiles"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profiles"
            }
          }
        }
      }
    },
    "/auth/signup": {
      "post": {
        "tags": ["AWS"],
        "summary": "Registro de usuario cognito",
        "parameters": [
          {
            "description": "name para el usuario de cognito",
            "name": "name",
            "in": "body",
            "required": true
          },
          {
            "description": "username para el usuario de cognito",
            "name": "username",
            "in": "body",
            "required": true
          },
          {
            "description": "email para el usuario de cognito",
            "name": "email",
            "in": "body",
            "required": true
          },
          {
            "name": "password",
            "description": "password para el usuario de cognito",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserCognito"
            }
          }
        ],
        "responses": {
          "200": {
            "description":
              "{ code:200, success:true, data:CognitoUser {username: 'TestUser', pool: CognitoUserPool { userPoolId: 'region_ID', clientId: 'xxxxxxxxxxxxxxx', client:[Object], storage: [Object] }, Session: null, client: Service { config: [Object], isGlobalEndpoint: false,endpoint: [Object],  _clientId: 1 }, signInUserSession: null, authenticationFlowType: 'USER_SRP_AUTH',storage: { [Function: MemoryStorage] setItem: [Function: setItem], getItem: [Function: getItem],removeItem: [Function: removeItem],clear: [Function: clear] } } }"
          },
          "400": {
            "description":
              "{'code':400, 'success':false, 'error':{'message':'Attributes did not conform to the schema: name:The attribute is required\n','code':'InvalidParameterException','time':'2018-01-29T18:16:32.139Z','requestId':'xxx-xx-xx-xx-xxxxx','statusCode':400,'retryable':false,'retryDelay':10.43321546356555}}"
          },
          "409": {
            "description":
              "Caso 1 : {code:409, 'success':false, error:'name/username/password/email Incorrect'},  Caso 2 : {'code':409, 'success':false, 'error':'Invalid email'}"
          }
        }
      }
    },
    "/auth/verification/code": {
      "post": {
        "tags": ["AWS"],
        "summary": "Confirmacion Manual de Codigo Cognito",
        "parameters": [
          {
            "description":
              "Se le envia al correo un codigo que debera confirmar",
            "name": "code",
            "in": "body",
            "required": true
          },
          {
            "description":
              "Tambien debera ingresar el username el cual esta confirmando",
            "name": "username",
            "in": "body",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description":
              "{code:200, success:true, data:'Successfully confirmed user'}"
          },
          "400": {
            "description": "{code:400, success:false, error:object}"
          }
        }
      }
    },
    "/auth/facebook": {
      "get": {
        "tags": ["Passport"],
        "summary": "Autenticacion con Facebook",
        "parameters": [
          {
            "description": "Correo de facebook.",
            "name": "correo",
            "in": "facebook",
            "required": true
          },
          {
            "description": "Password de facebook.",
            "name": "password",
            "in": "facebook",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description":
              "{'code':200,'success':true,'user':{'id':'xxxxx','displayName':'Pedro Pereza','name':{},'gender':'male','profileUrl':'https://www.facebook.com/app_scoped_user_id/xxxxxxxx/','emails':[{'value':'pedro@yopmail.com'}],'photos':[{'value':'https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/xx.jpg?oh=xx&oe=xx'}],'provider':'facebook','_raw':'{'id':'xxx','name':'Pedro Pereza','link':'https:\\/\\/www.facebook.com\\/app_scoped_user_id\\/xxx\\/','picture':{'data':{'height':50,'is_silhouette':false,'url':'https:\\/\\/scontent.xx.fbcdn.net\\/v\\/t1.0-1\\/p50x50\\/xx.jpg?oh=xx&oe=5B25FF0E','width':50}},'email':'pedro@yopmail.com','gender':'male'}','_json':{'id':'xx','name':'Pedro Pereza','link':'https://www.facebook.com/app_scoped_user_id/xxxxx/','picture':{'data':{'height':50,'is_silhouette':false,'url':'https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/xx.jpg?oh=xx&oe=xx','width':50}},'email':'pedro@yopmail.com','gender':'male'}}} "
          },
          "400": {
            "description":
              "{'code':400, 'success':false, 'error':'Invalid Provider'}"
          },
          "500": {
            "description": "{code:500, 'success':false, error:object}"
          }
        }
      }
    },
    "/auth/google": {
      "get": {
        "tags": ["Passport"],
        "summary": "Autenticacion con Google",
        "parameters": [
          {
            "description": "Correo de google.",
            "name": "correo",
            "in": "google",
            "required": true
          },
          {
            "description": "Password de google.",
            "name": "password",
            "in": "google",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description":
              "{'code':200,'success':'true','user':{'id':'xx','displayName':'pedro perez','name':{'familyName':'perez','givenName':'pedro'},'emails':[{'value':'pedro@yopmail.com','type':'account'}],'photos':[{'value':'https://lh4.googleusercontent.com/-E1XT6qrCa2M/AAAAAAAAAAI/AAAAAAAAAR4/es66j2-iACA/photo.jpg?sz=50'}],'gender':'male','provider':'google','_raw':'{ 'kind': 'plus#person', 'etag': 'xxxx/xxxxx', 'gender': 'male', 'emails': [  {'value': 'pedro@yopmail.com',  'type': 'account'}], 'objectType': 'person', 'id': 'xxx', 'displayName': 'pedro perez', 'name': {  'familyName': 'perez',  'givenName': 'pedro' }, 'url': 'https://plus.google.com/xxxxx', 'image': {  'url':'https://lh4.googleusercontent.com/-E1XT6qrCa2M/AAAAAAAAAAI/AAAAAAAAAR4/es66j2-iACA/photo.jpg?sz=50',  'isDefault': 'false' }, 'isPlusUser': true, 'language': 'es', 'circledByCount': 0, 'verified': false, 'cover': { 'layout': 'banner',  'coverPhoto': { 'url': 'https://lh3.googleusercontent.com/xxxx=s630-fcrop64=1,00000000fffff155', 'height': 562, 'width': 940 },'coverInfo': { 'topImageOffset': -276, 'leftImageOffset': 0}}}','_json':{'kind':'plus#person','etag':'xx/xx','gender':'male','emails':[{'value':'pedro@yopmail.com','type':'account'}],'objectType':'person','id':'xxx','displayName':'pedro' 'perez','name':{'familyName':'perez','givenName':'pedro'},'url':'https://plus.google.com/xx',image':{'url':'https://lh4.googleusercontent.com/-E1XT6qrCa2M/AAAAAAAAAAI/AAAAAAAAAR4/es66j2-iACA/photo.jpg?sz=50','isDefault':false},'isPlusUser':true,'language':'es','circledByCount':0,'verified':false,'cover':{'layout':'banner','coverPhoto':{'url':'https://lh3.googleusercontent.com/xxxxx=s630-fcrop64=1,00000000fffff155','height':562,'width':940},'coverInfo':{'topImageOffet':-276,'leftImageOffset':0}}}}}"
          },
          "400": {
            "description":
              "{'code':400, 'success':false, 'error':'Invalid Provider'}"
          },
          "500": {
            "description": "{code:500, 'success':false, error:object}"
          }
        }
      }
    },
    "/auth/cognito": {
      "post": {
        "tags": ["Passport"],
        "summary": "Autenticacion con Cognito",
        "parameters": [
          {
            "description": "username de cognito",
            "name": "username",
            "required": true,
            "in": "body"
          },
          {
            "name": "password",
            "description": "password de cognito",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserCognitoGeneral"
            }
          }
        ],
        "responses": {
          "200": {
            "description":
              "{'code':200, 'success':true,'user':{'sub':'xxx-xx-xx-xx-xx','email_verified':'true','name':'Pedro Pereza','email':'aperez@yopmail.com','username':'aperez'}}"
          },
          "400": {
            "description": "{'code':400, 'error':'Invalid Provider'}"
          },
          "409": {
            "description":
              "{code:409, success:false, error:'Error authenticating the user, or it is necessary to confirm the code '}"
          },
          "500": {
            "description": "{code:500, success:false, error:object}"
          }
        }
      }
    },
    "/widgets/:id": {
      "get": {
        "tags": ["Widgets"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Parametro de busqueda de inicio",
            "required": true
          },
          {
            "in": "query",
            "name": "start",
            "description": "Parametro de busqueda de inicio"
          },
          {
            "in": "query",
            "name": "end",
            "description": "Parametro de busqueda de finalizacion"
          },
          {
            "in": "query",
            "name": "scale",
            "description": "Parametro de busqueda para la escala del tiempo"
          }
        ],
        "summary": "Obtiene la informacion para graficas",
        "description":
          "Obtiene la informacion para graficas segun el valor del Id \nPara obtener perfiles detectados por periodo de tiempo: /widgets/clientHour\nPara obtener perfiles detectados por ubicacion: /widgets/clientLocation\nPara obtener perfiles sociales detectados por periodo de tiempo: /widgets/providerHour\nPara obtener el total de perfiles sociales detectados: /widgets/providerTotal\nPara obtener perfiles por genero en un periodo de tiempo: /widgets/genderHour\nPara obtener el total de perfiles por genero: /widgets/genderTotal\n",
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "400": {
            "description": "Id de grafica invalida"
          }
        }
      }
    }
  },
  "definitions": {
    "UserCognito": {
      "required": ["email", "password", "name", "username"],
      "properties": {
        "password": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "uniqueItems": true
        },
        "name": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      },
      "example": {
        "pasword": "lovescurity",
        "email": "a@mail.com",
        "name": "Anonimus",
        "username": "anonym"
      }
    },
    "UserCognitoGeneral": {
      "required": ["password", "username"],
      "properties": {
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      },
      "example": {
        "password": "lovesecurity",
        "username": "anonymus"
      }
    },
    "Locations": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "example": {
        "id": 2,
        "name": "Algun lado",
        "latitude": -34.56785,
        "longitude": -56.2343,
        "createdAt": "2018-02-22T15:10:53.960Z",
        "updatedAt": "2018-02-22T15:11:43.960Z"
      }
    },
    "Locationspost": {
      "properties": {
        "name": {
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        }
      },
      "example": {
        "name": "Algun lado",
        "latitude": -34.56785,
        "longitude": -56.2343
      }
    },
    "Locationsput": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        }
      },
      "example": {
        "id": "1234y9230nasdc0",
        "name": "Algun lado",
        "latitude": -34.66785,
        "longitude": -57.2343
      }
    },
    "Locationsput2": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "example": {
        "id": "1234y9230nasdc0",
        "name": "Algun lado",
        "latitude": -34.66785,
        "longitude": -57.2343,
        "updatedAt": "2018-02-22T15:10:53.960Z"
      }
    },
    "Locationsdelete": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "example": {
        "id": "1234y9230nasdc0"
      }
    },
    "APs": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "locationId": {
          "type": "string"
        },
        "locationName": {
          "type": "string"
        },
        "tags": {
          "type": "string"
        },
        "state": {
          "type": "boolean"
        },
        "mac": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "example": {
        "id": 1,
        "name": "Prueba 157",
        "locationName": "Chacra",
        "locationId": "1231sd12",
        "state": 0,
        "tags": ["prueba"],
        "mac": "F0:E1:D2:C3:B4:A5",
        "createdAt": "2018-02-22T15:10:53.960Z",
        "updatedAt": "2018-02-22T15:11:43.960Z"
      }
    },
    "APsput": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "example": {
        "id": 1,
        "name": "Prueba 159"
      }
    },
    "APsput2": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        }
      },
      "example": {
        "id": 1,
        "name": "Prueba 159",
        "createdAt": "2018-02-22T15:10:53.960Z"
      }
    },
    "APsdelete": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "example": {
        "id": 1
      }
    },
    "APspost": {
      "properties": {
        "name": {
          "type": "string"
        },
        "locationId": {
          "type": "string"
        },
        "locationName": {
          "type": "string"
        },
        "tags": {
          "type": "array"
        },
        "state": {
          "type": "boolean"
        },
        "mac": {
          "type": "string"
        }
      },
      "example": {
        "name": "Prueba 157",
        "locationName": "Chacra",
        "locationId": "1231sd12",
        "state": 0,
        "tags": ["prueba", "hola"],
        "mac": "F0:E1:D2:C3:B4:A5"
      }
    },
    "Profiles": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "age": {
          "type": "string"
        },
        "deviceMac": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "emailVerified": {
          "type": "boolean"
        },
        "doc": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "example": {
        "id": 2,
        "name": "Jane Doe",
        "email": "anonymus@mail.com",
        "emailVerified": true,
        "picture": "www.google.com/apcia/pict",
        "age": 18,
        "deviceMac": "85:4f:34:25",
        "doc": "afqeda2",
        "gender": "male",
        "provider": "local",
        "sub": "qdbiwod4",
        "createdAt": "2018-02-22T15:10:53.960Z",
        "updatedAt": "2018-02-22T15:11:43.960Z"
      }
    },
    "Profilespost": {
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "string"
        },
        "deviceMac": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "emailVerified": {
          "type": "boolean"
        },
        "doc": {
          "type": "string"
        }
      },
      "example": {
        "name": "Jane Doe",
        "email": "anonymus@mail.com",
        "emailVerified": true,
        "picture": "www.google.com/apcia/pict",
        "age": 18,
        "deviceMac": "85:4f:34:25",
        "doc": "afqeda2",
        "gender": "male",
        "provider": "local",
        "sub": "qdbiwod4"
      }
    },
    "Profilesput": {
      "properties": {
        "deviceMac": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "emailVerified": {
          "type": "boolean"
        }
      },
      "example": {
        "emailVerified": true,
        "deviceMac": "85:4f:34:25",
        "provider": "local",
        "sub": "qdbiwod4"
      }
    },
    "Profilesput2": {
      "properties": {
        "deviceMac": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "emailVerified": {
          "type": "boolean"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "example": {
        "updatedAt": "2018-02-22T15:10:53.960Z",
        "emailVerified": true,
        "deviceMac": "85:4f:34:25",
        "provider": "local",
        "sub": "qdbiwod4"
      }
    },
    "Profilesdelete": {
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "example": {
        "id": "21dcc329dn2"
      }
    },
    "ArrayOfProfiles": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Profiles"
      },
      "example": [
        {
          "id": 2,
          "name": "Jane Doe",
          "email": "anonymus@mail.com",
          "emailVerified": true,
          "picture": "www.google.com/apcia/pict",
          "age": 18,
          "deviceMac": "85:4f:34:25",
          "doc": "afqeda2",
          "gender": "male",
          "provider": "local",
          "sub": "qdbiwod4",
          "createdAt": "2018-02-22T15:10:53.960Z",
          "updatedAt": "2018-02-22T15:11:43.960Z"
        },
        {
          "id": 3,
          "name": "James Rodriguez",
          "email": "jr@mail.com",
          "emailVerified": true,
          "picture": "www.google.com/apcia/pict2",
          "age": 24,
          "deviceMac": "85:4f:34:25",
          "doc": "afsqeda2",
          "gender": "male",
          "provider": "google",
          "sub": "qdbiwod41",
          "createdAt": "2018-02-22T15:10:53.960Z",
          "updatedAt": "2018-02-22T15:11:43.960Z"
        }
      ]
    },
    "ArrayOfAps": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/APs"
      },
      "example": [
        {
          "id": 1,
          "name": "Prueba 157",
          "locationName": "Chacra",
          "locationId": "1231sd12",
          "state": 0,
          "tag": "prueba",
          "mac": "F0:E1:D2:C3:B4:A5",
          "createdAt": "2018-02-22T15:10:53.960Z",
          "updatedAt": "2018-02-22T15:11:43.960Z"
        },
        {
          "id": 1,
          "name": "Prueba 153",
          "locationName": "Oficina",
          "locationId": "1231sd11",
          "state": 0,
          "tag": "prueba",
          "mac": "F0:E1:D4:C3:B4:A5",
          "createdAt": "2018-02-22T15:10:53.960Z",
          "updatedAt": "2018-02-22T15:11:43.960Z"
        }
      ]
    },
    "ArrayOfLocations": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Locations"
      },
      "example": [
        {
          "id": 38,
          "name": "Oficina",
          "latitude": -34.56785,
          "longitude": -56.234,
          "createdAt": "2018-02-22T15:10:53.960Z",
          "updatedAt": "2018-02-22T15:11:43.960Z"
        },
        {
          "id": 112,
          "name": "Plaza de Comidas",
          "latitude": -34.56785,
          "longitude": -57.234,
          "createdAt": "2018-02-22T15:10:53.960Z",
          "updatedAt": "2018-02-22T15:11:43.960Z"
        }
      ]
    }
  }
}
